[package]
name = "opla"
version = "0.0.1"
edition = "2021"
default-run = "opla-cli"


[[bin]]
bench = false
path = "crates/cli/src/main.rs"
name = "opla-cli"

[workspace]
members = [
  "crates/tokenizer",
  "crates/cli",
  "webapp/native"
]

