# Dirty hack to fix Windows version not fully compatible with semver
[package]
version = "1.0.237"
# fix missing dll files for Windows version
[tauri.bundle.resources]
"binaries/llama.cpp/llama.dll" = "./"
"binaries/llama.cpp/ggml.dll" = "./"
"assets/opla_default_config.json" = "assets/"
"assets/default_presets.json" = "assets/"
"assets/default_providers.json" = "assets/"
"assets/default_assistants.json" = "assets/"
