[package]
name = "opla_core"
version = "1.0.0-alpha.227"
edition = "2021"

include = ["src/**/*"]

[dependencies]
anyhow = "1.0.76"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
